name: Build
run-name: Build tree-sitter-metamodelica

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Clean install
        run: npm ci
      - name: Run build script
        run: npm run build
      - name: Run test script
        run: npm test

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-metamodelica.wasm
          path: |
            tree-sitter-metamodelica.wasm
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: tree-sitter-metamodelica.wasm

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tree-sitter-metamodelica.wasm
          fail_on_unmatched_files: true
          generate_release_notes: true
          append_body: true
